'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.9151
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("FEConfigurator.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''	&lt;!--
        '''	UseRegistry - TRUE or FALSE. If You want Fable Explorer to lookup your install - use this as TRUE
        '''	RegistryPath - The path that it seeks in the registry by default
        '''	InstallDirectory - If UseRegistry is False, it will look for Fable.exe or default.xbe (Xbox) in your specified path to verify it is correct
        '''	InternalSplash - TRUE or FALSE. If you want to use a different splash than the one that is compiled it must be set to FALSE
        '''	SplashFileName - If FALSE it  [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property config() As String
            Get
                Return ResourceManager.GetString("config", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;!--
        '''
        '''  Valid Member Types
        '''  (Type name)             (Description)
        '''  int                     32 bit signed integer
        '''  uint                    32 bit unsigned integer
        '''  short                   16 bit signed integer
        '''  ushort                  16 bit unsigned integer
        '''  char                    8 bit signed integer
        '''  byte                    8 bit unsigned integer
        '''  string                  Null-terminated string (c-style string)
        '''  float                   32 bit flo [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property def() As String
            Get
                Return ResourceManager.GetString("def", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property header() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("header", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Click here to specify the location of Fable game files..
        '''</summary>
        Friend ReadOnly Property infotext_click_to_edit_path() As String
            Get
                Return ResourceManager.GetString("infotext_click_to_edit_path", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Close Fable Explorer Configurator. Any unsaved changes will be lost!.
        '''</summary>
        Friend ReadOnly Property infotext_close() As String
            Get
                Return ResourceManager.GetString("infotext_close", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Select this option if you want to find Fable by hand. USE THIS WITH MODERN WINDOWS! (Vista and up), especially on 64 bit systems..
        '''</summary>
        Friend ReadOnly Property infotext_from_filepath() As String
            Get
                Return ResourceManager.GetString("infotext_from_filepath", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Select this option if Fable Explorer should find Fable game files automatically. MAY NOT WORK ON STEAM RELEASE!.
        '''</summary>
        Friend ReadOnly Property infotext_from_registry() As String
            Get
                Return ResourceManager.GetString("infotext_from_registry", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Check out this project on GitHub!.
        '''</summary>
        Friend ReadOnly Property infotext_github() As String
            Get
                Return ResourceManager.GetString("infotext_github", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Save configuration and exit Fable Explorer Configurator..
        '''</summary>
        Friend ReadOnly Property infotext_saveexit() As String
            Get
                Return ResourceManager.GetString("infotext_saveexit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Use custom splash image file, when launching Fable Explorer..
        '''</summary>
        Friend ReadOnly Property infotext_use_custom_splash() As String
            Get
                Return ResourceManager.GetString("infotext_use_custom_splash", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
